import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <Link href='/csr'>
        <p className={styles.link}>
          Go to Client Side Rendering
        </p>
      </Link>
      <Link href='/server-page'>
        <p className={styles.link}>
          Go to Server Side Rendering
        </p>
      </Link>
      <Link href='/static-page'>
        <p className={styles.link}>
          Go to Cached Pages
        </p>
      </Link>
      <Link href='/isr'>
        <p className={styles.link}>
          Go to Incremental static site generation
        </p>
      </Link>
      <Link href='/isr-test'>
        <p className={styles.link}>
          Go to on-demand Incremental static site generation
        </p>
      </Link>
    </div>
  )
}
